import { DiffContext, NullKnowledgeBase } from './context';
import { BenchmarkCollector } from './benchmark/collector';
import { AlgorithmRegistry } from './algorithms/registry';

// Algorithms
import { MyersDiff } from './algorithms/myers';
import { HistogramDiff } from './algorithms/histogram';
import { PatienceDiff } from './algorithms/patience';
import { BinaryDiff } from './algorithms/binary';
import { ASTDiff } from './algorithms/ast';

// Pipeline Stages
import { ValidatorStage } from './pipeline/validator';
import { NormalizerStage } from './pipeline/normalizer';
import { PartitionEngineStage } from './pipeline/partition-engine';
import { MovementEstimatorStage } from './pipeline/movement-estimator';
import { GraphFeatureExtractorStage } from './pipeline/graph-feature-extractor';
import { QueryPlannerStage } from './pipeline/query-planner';
import { SchedulerStage } from './pipeline/scheduler';
import { EditOptimizerStage } from './pipeline/edit-optimizer';
import { CharacterRefinerStage } from './pipeline/character-refiner';
import { PatchASTBuilderStage } from './pipeline/patch-ast-builder';
import { SerializersStage } from './pipeline/serializers';
import { OutputBuilderStage } from './pipeline/output-builder';

import type {
  DiffInput,
  DiffResult,
  IPipelineStage,
  DiffMetadata,
  FileFeatures,
  DiffStatistics,
} from './types';

// ---------------------------------------------------------------------------
// Safe defaults for edge-case paths (identical files, binary files)
// ---------------------------------------------------------------------------

const DEFAULT_FILE_FEATURES: FileFeatures = {
  fileSize: 0,
  lineCount: 0,
  averageLineLength: 0,
  maxLineLength: 0,
  duplicateLineRatio: 0,
  uniqueLineRatio: 1,
  entropy: 0,
  language: 'plaintext',
  isBinary: false,
  isGenerated: false,
  encoding: 'utf-8',
  extension: '',
};

const DEFAULT_STATISTICS: DiffStatistics = {
  totalLines: 0,
  addedLines: 0,
  deletedLines: 0,
  modifiedLines: 0,
  unchangedLines: 0,
  addedCharacters: 0,
  deletedCharacters: 0,
  moveCount: 0,
  editCount: 0,
  patchSizeBytes: 0,
};

// ---------------------------------------------------------------------------
// DiffEngine — public API
// ---------------------------------------------------------------------------

export class DiffEngine {
  private registry: AlgorithmRegistry;
  private pipeline: IPipelineStage[];

  constructor() {
    this.registry = new AlgorithmRegistry();

    // Register algorithms
    this.registry.register(new MyersDiff());
    this.registry.register(new HistogramDiff());
    this.registry.register(new PatienceDiff());
    this.registry.register(new BinaryDiff());
    this.registry.register(new ASTDiff());

    // Build V3 pipeline
    this.pipeline = [
      new ValidatorStage(),
      new NormalizerStage(),
      new PartitionEngineStage(),
      new MovementEstimatorStage(),
      new GraphFeatureExtractorStage(),
      new QueryPlannerStage(this.registry),
      new SchedulerStage(this.registry),
      new EditOptimizerStage(),
      new CharacterRefinerStage(),
      new PatchASTBuilderStage(),
      new SerializersStage(),
      new OutputBuilderStage(),
    ];
  }

  /**
   * Compare two versions of a file and produce a rich diff result.
   */
  compare(input: DiffInput): DiffResult {
    const collector = new BenchmarkCollector();
    collector.start();

    // In a real integration, the KB would be injected.
    const kb = new NullKnowledgeBase();
    const ctx = new DiffContext(input, kb); // This is the memory at which the ctx is pointing, so that when we pass something its the reference we pass. 

    for (const stage of this.pipeline) {
      const done = collector.beginStage(stage.name);
      stage.execute(ctx);
      done();
    }

    ctx.benchmarks = collector.collect();

    const metadata: DiffMetadata = {
      oldFileFeatures: ctx.oldFileFeatures ?? { ...DEFAULT_FILE_FEATURES, isBinary: ctx.binary },
      newFileFeatures: ctx.newFileFeatures ?? { ...DEFAULT_FILE_FEATURES, isBinary: ctx.binary },
      identical: ctx.identical,
      binary: ctx.binary,
      timedOut: ctx.timedOut,
      fallbackUsed: ctx.fallbackUsed,
      fallbackReason: ctx.fallbackReason,
    };

    const statistics: DiffStatistics = ctx.statistics ?? {
      ...DEFAULT_STATISTICS,
      unchangedLines: ctx.normalizedOld?.lines.length ?? 0,
      totalLines: ctx.normalizedNew?.lines.length ?? ctx.normalizedOld?.lines.length ?? 0,
    };

    return {
      regionalSelections: Array.from(ctx.regionalSelections.values()),
      operations: ctx.optimizedEditScript,
      characterChanges: ctx.characterChanges,
      moves: ctx.moveAnchors,
      patchAST: ctx.patchAST!, // generated by PatchASTBuilder
      patches: ctx.patches,
      statistics,
      benchmarks: ctx.benchmarks,
      metadata,
    };
  }
}

export * from './types';
